### ISSUE TITLE
new future --import -export to field

### ISSUE THREAD

**Issue by shikulja** [myst6re/vincent-tim#10]
That would be awesome, one program to rule the whole game.

so far I have not found more than one program that can work with field archives from the command line

**Comment by myst6re** [comment]
Too big for this project

**Comment by shikulja** [comment]
@myst6re 
but a very useful feature, one could use deling for this if it supported cli.
There is still nothing similar.

**Comment by myst6re** [comment]
I moved this ticket to Deling
