### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by shikulja** [myst6re/vincent-tim#11]
```
set TIM=".\tools\TIM"
set PNGE=PNG_EDITED
set TEXI=TEX_IMPORT
for /F %%x in ("%PNGE%\iconfl**.*.2.png") do ("%TIM%\tim" --if png --of tex -p 2 "%%x" "%TEXI%")
```

for "%TEXI%" as output folder save tim to parent folder, not in TEX_IMPORT, 
i think v-tools - does not account for quotes in the output folder path

**Comment by shikulja** [comment]
my mistake
if not exist .\"%PNGO%"\ (
mkdir "%PNGE%"
mkdir "%PNGO%"
mkdir TEX_ORIG
mkdir "%TEXI%"
::mkdir TIM_IMPORT
)
cannot use comment inside

**Comment by myst6re** [comment]
Oh good, thanks for your ticket anyway :-)
