### ISSUE TITLE
Editing BMP from 

### ISSUE THREAD

**Issue by rhadamants** [myst6re/vincent-tim#5]
I'm trying to edit a PNG or BMP file by creating and using Paint or PhotoShop accuses "Error: Colors in the image does not match with the palette, have you changed some colors"How do you edit the pictures?

**Comment by myst6re** [comment]
Do you confirm this bug still hapen with Vincent Tim 1.2 ?

**Comment by rhadamants** [comment]
I'm using version 1.1. To avoid this problem have to use Windows XP mspaint

**Comment by myst6re** [comment]
Try with [version 1.2](https://github.com/myst6re/vincent-tim/releases/download/v1.2/Vincent-Tim-v1.2.zip)
