### ISSUE TITLE
Error when Import png file to a texture

### ISSUE THREAD

**Issue by dragoncrest** [myst6re/vincent-tim#6]
I run this command: tim --if png --of tim -p 1 foo.tim.1.png output_directory
And it only show:
QImage::pixelIndex: Not applicable for 32-bpp images (no palette)
Could you tell me what is this problem?

**Comment by myst6re** [comment]
When you modified the file foo.tim.1.png, did you preserve the paletted 8-bit PNG format?

**Comment by dragoncrest** [comment]
I don't know about it, i just change and save back to the original file
